//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_003Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoscabe
    {
        public int IdPedido { get; set; }
        public string IdCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string EnvioPedido { get; set; }
        public Nullable<int> CantidaPedido { get; set; }
        public string Destinatario { get; set; }
        public string DirDestinatario { get; set; }
        public string CiuDestinatario { get; set; }
        public string RefDestnatario { get; set; }
        public string DepDestinatario { get; set; }
        public string PaiDestinatario { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
